In [0]:
a = 2
b = 4
c = a + b
print(c)

6


In [0]:
a = input("Enter first number")
b = input("enter second number")
c = input("enter third number")
if a > b and a > c:
  print("a is greatest")
if b > a and b > c:
  print("b is greatest")
if c > a and c > b:
  print("c is greatest")

Enter first number3
enter second number5
enter third number4
b is greatest


In [0]:
# printing fibonacci series
a = 0
b = 1
n = 7
fibonacci = []
c = []
for i in range(n):
  c = a + b
  fibonacci.append(c)
  a = b
  b = c
  
print(fibonacci)

[1, 2, 3, 5, 8, 13, 21]


In [0]:
  import numpy as np
  vector_row = np.array([1,2,3])
  vector_column = np.array([[1],[2],[3]])

In [0]:
print(vector_row)

[1 2 3]


In [0]:
print(vector_column)

[[1]
 [2]
 [3]]


In [0]:
import random
import numpy as np
a = np.random.randint(low=1,high=10,size=(3,3))
b = np.random.randint(low=10,high=20,size=(3,3))
print(a)
print(b)

[[1 5 4]
 [6 7 6]
 [2 1 2]]
[[10 18 16]
 [17 12 18]
 [19 17 17]]


In [0]:
dot_product = np.dot(a,b)
cross_product = np.cross(a,b)
addition = np.add(a,b)
print("Dot product of two vectors:")
print(dot_product)
print("Cross product of two vectors")
print(cross_product)
print("Vector Addition:")
print(addition)

Dot product of two vectors:
[[171 146 174]
 [293 294 324]
 [ 75  82  84]]
Cross product of two vectors
[[  8  24 -32]
 [ 54  -6 -47]
 [-17   4  15]]
Vector Addition:
[[11 23 20]
 [23 19 24]
 [21 18 19]]


In [0]:
import pandas as pd
data = pd.read_csv("Iris.csv")

In [32]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [33]:
pd.isnull(data)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
5    False          False         False          False         False    False
6    False          False         False          False         False    False
7    False          False         False          False         False    False
8    False          False         False          False         False    False
9    False          False         False          False         False    False
10   False          False         False          False         False    False
11   False          False         False          False         False    False
12   False          False         False          False         False    False
13   False          False         False          False         False    False
14   False          False         False          False         False    False
15   False          False         False          False         False    False
16   False          False         False          False         False    False
17   False          False         False          False         False    False
18   False          False         False          False         False    False
19   False          False         False          False         False    False
20   False          False         False          False         False    False
21   False          False         False          False         False    False
22   False          False         False          False         False    False
23   False          False         False          False         False    False
24   False          False         False          False         False    False
25   False          False         False          False         False    False
26   False          False         False          False         False    False
27   False          False         False          False         False    False
28   False          False         False          False         False    False
29   False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
120  False          False         False          False         False    False
121  False          False         False          False         False    False
122  False          False         False          False         False    False
123  False          False         False          False         False    False
124  False          False         False          False         False    False
125  False          False         False          False         False    False
126  False          False         False          False         False    False
127  False          False         False          False         False    False
128  False          False         False          False         False    False
129  False          False         False          False         False    False
130  False          False         False          False         False    False
131  False          False         False          False         False    False
132  False          False         False          False         False    False
133  False          False         False          False         False    False
134  False          False         False          False         False    False
135  False          False         False          False         False    False
136  False          False         False          False         False    False
137  False          False         False          False         False    False
138  False          False         False          False         False    False
139  False          False     

In [34]:
data.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [0]:
diabetes = pd.read_csv("diabetes.csv")

In [36]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [38]:
diabetes.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [0]:
diabetes1 = pd.read_csv("pima-indians-diabetes.csv", header = None)

In [44]:
diabetes1.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [45]:
diabetes1.isna().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

In [0]:
import pandas as pd
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, np.nan, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df = pd.DataFrame(data)

In [55]:
df.head()

state    year  pop
0    Ohio  2000.0  1.5
1    Ohio  2001.0  1.7
2    Ohio  2002.0  3.6
3  Nevada  2001.0  2.4
4  Nevada     NaN  2.9

In [56]:
df.dropna()

state    year  pop
0    Ohio  2000.0  1.5
1    Ohio  2001.0  1.7
2    Ohio  2002.0  3.6
3  Nevada  2001.0  2.4
5  Nevada  2003.0  3.2

In [57]:
df.fillna(0)

state    year  pop
0    Ohio  2000.0  1.5
1    Ohio  2001.0  1.7
2    Ohio  2002.0  3.6
3  Nevada  2001.0  2.4
4  Nevada     0.0  2.9
5  Nevada  2003.0  3.2

In [0]:
state = df["state"]

In [59]:
print(state)

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object


In [81]:
#df.set_index("state")
df.loc[:,"state"]


0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [67]:
df.iloc[3:5,]

state    year  pop
3  Nevada  2001.0  2.4
4  Nevada     NaN  2.9

In [85]:
df1 = pd.read_csv("paralleltrack1.csv")
df2 = pd.read_csv("paralleltrack2.csv")
df1.head()


country  lap1  lap2  lap3  lap4
0       India  12.7  13.2  12.9    14
1  Bangladesh  12.5  13.0  12.9    14
2   sri Lanka  13.0  12.2  14.0    13

In [84]:
df2.head()

country  lap1  lap2  lap3  lap4
0      UK  13.0  12.5  12.1    12
1  France  13.4  13.1  12.6    13
2  Sweden  13.2  12.8  12.7    13

In [0]:
df = pd.concat([df1,df2])

In [91]:
df

country  lap1  lap2  lap3  lap4
0       India  12.7  13.2  12.9    14
1  Bangladesh  12.5  13.0  12.9    14
2   sri Lanka  13.0  12.2  14.0    13
0          UK  13.0  12.5  12.1    12
1      France  13.4  13.1  12.6    13
2      Sweden  13.2  12.8  12.7    13

In [0]:
df = pd.concat([df1,df2],ignore_index=True)

In [93]:
df

country  lap1  lap2  lap3  lap4
0       India  12.7  13.2  12.9    14
1  Bangladesh  12.5  13.0  12.9    14
2   sri Lanka  13.0  12.2  14.0    13
3          UK  13.0  12.5  12.1    12
4      France  13.4  13.1  12.6    13
5      Sweden  13.2  12.8  12.7    13